### PR TITLE
Fixed title screen text, and exit button changed to Reset button

### PR DESCRIPTION
**Pull request by Rezzy-dev**

### CODE REVIEW

**Comment by szymor** [comment]
Well, I can merge it, but did you know that v1 branch contains SDL 1.2 version of the game? Just asking to be sure your changes are intentional.

**Comment by szymor** [comment]
Regarding text fixes and other changes related to porting to Miyoo - good job :) The only thing I do not like is that a part of the code is not in English anymore, but it is not an official repository of the game, so let it be.

**Comment by szymor** [comment]
I thought more about your changes. main.c was taken directly from the old v1 version. In the end I would prefer not to merge it as it is now.
On the other hand I would happily cherry-pick your changes regarding bug fixing, but I need to review and merge them when I have more time. Therefore, I will leave this PR open for the time being. Thank you for cooperation!

**Comment by Rezzy-dev** [comment]
Thanks. I wasn't going to fork and submit a pull request -- I was just going to send you the updated images and fix suggestion in an issue/discussion, but neither issues nor discussions are enabled for this repository, so the only option I had was to fork and send the changes upstream for you to see.

It's fine if you don't merge this into the main repository. Just take the images and the button fix in main.c (from SDLK_ESCAPE to SDLK_RCTRL for Miyoo devices, which sets the menu button to the Reset button).

It's odd that the source code in the repository and the source code for the release are not in sync given that the release says no changes were made to the source code since -- but I suppose this is a GitHub mixup/error. That's what led me astray, thinking I was grabbing the most current source from the release. I was surprised to find the great differences when I tried to send the fixed source upstream.

It doesn't matter, though. The main thing is that you have the changes. I compiled this source successfully and the changes work great on a PowKiddy Q90.

This pull request is just two fixed/updated images and a simple code fix (SDLK_ESCAPE to SDLK_CTRL).

The rest is unexpected differences between the source code in your repository and the source code supplied for the release. No need to merge them -- and in fact you shouldn't.

**Comment by szymor** [comment]
The release and the source code are, in fact, in sync. The release is just for v1 branch, which is noted if you read carefully ;) I am just unable to change the default branch on my fork for some reason.
The best solution would be if you moved your changes to v1 branch and then create PR. If not, do not worry - I will keep in mind your changes and merge them if I ever release a newer binary.
Sorry for lack of issues/discussion tab - by default these options are disabled on forks by GitHub. If you ever wanted to contact me again, you can grab my e-mail from git repository's history, too. ;p

**Comment by Rezzy-dev** [comment]
It looks like I ended up making an error -- mixing the two sources when I forked from you.

Grab only the fixed/updated images, and the fix suggestion for the button (to RCTRL). I'll remove my fork of the repository, as it's actually faulty due to the mixup.

**Comment by Rezzy-dev** [comment]
You can also grab the pre-built package, as it's just the v1 source with these simple changes. You could make it the updated v1 build for Miyoo. I already did the work building it.

**Comment by Rezzy-dev** [comment]
Just diff main.c in my repository with the v1 main.c, and you'll see the two lines where the change was made. It's no big change, just a small fix. And an update to the two images to fix the title screen texts.

**Comment by szymor** [comment]
Well, I cannot promise I will do any update soon (I really lack of time for any software development ;( ), so if you do not plan to make a new PR for v1 branch, please do not remove your fork from GH.

**Comment by Rezzy-dev** [comment]
Oh... okay. I'll see about doing this again, then, using the v1 branch... *Sighs.* No worries. I just didn't figure I needed to do so much work to upload a small fix. (GitHub really shits me sometimes.)

I still have the source on my computer, so I can re-upload all this to the v1 branch. I just need to find the time to do it again.

**Comment by szymor** [comment]
Thank you for your effort <3 Unfortunately, GitHub does not have a good UI regarding work on different branches, I would expect it to highlight the recently updated branch. Switching the default branch is also not an option here because it simply does not work for some repos from my profile (weird, really).
Git is not ideal, too - moving your changes to the older branch implies moving all the commits down the common history commit, too, which is absurd. I would expect moving features to be implemented as applying a diff file, but it is as it is.
I am waiting for your new PR then. Do not feel obliged, though. It is just a hobby ;)

**Comment by szymor** [comment]
FYI, I changed the default branch to sdl1 a while ago. I could not change it earlier because there is a bug in the mobile version of GitHub which prevented me to do so.

**Comment by Rezzy-dev** [comment]
Ah, kudos! 🎉  \*^_^\*

Thanks @szymor. Yeah, GitHub's handling of certain things is really-really unintuitive and weird -- quite a bad design. And repository "branches" are one of the things that I hear a lot of trouble with. Personally, I don't even use the branches, I just create a new repository for a new branch, and manage things from the computer end as opposed to GitHub's web end, and just sync/upload the changes to GitHub.

I can't be bothered dealing with their nonsense. I need to save my braincells for more productive things. :P

And, yeah, Git has its fair share of missing/hidden features and bad design choices, too (although far less than GitHub).

I'll see if I can find the time to go through the files and re-upload the changes (to the right repository/branch this time) this weekend. I'm sure these updates will come in handy for Miyoo users -- even if they're essentially minor details/fixes.

**Comment by Rezzy-dev** [comment]
Also, I wanted to warn you that GitHub does one other weird/unnoted/unexplained thing:

When you upload a release file (a binary download), it packs the current state of the main repository as the source code for that release, and NEVER updates this! So, depending on when you uploaded the release, you can have old or nonfunctional source code attached to it, or a completely different source/branch than the one the release/binary was made from.

Totally confusing and nonsensical design that can lead to big confusion/problems if other users download that source code ZIP, thinking it's the source for the build, as noted.

So just be aware of this. When you upload a new release, or reupload the same file as a new release, the current state of the main branch/repository will be packed into the source code ZIP. That's the only way (as far as I know) to update that ZIP -- which is ridiculous.

**Comment by szymor** [comment]
Good to know, thx :) Waiting for your changes then.

**Comment by szymor** [comment]
Closed as it is not gonna be merged into the master branch anyway.

**Pull request closed without merging**
